# Generated by Django 2.2.5 on 2019-09-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellar', '0004_auto_20160918_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='qrcode_file',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
