# Generated by Django 2.2.5 on 2019-10-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellar', '0005_auto_20190926_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_name', models.CharField(max_length=200)),
                ('last_logout', models.DateTimeField(auto_now_add=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='mobile_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='seed',
            field=models.CharField(max_length=800),
        ),
    ]
